### PR TITLE
fix: ensure that the name is added to the wrangler.toml file during init

### PR DESCRIPTION
**Pull request by petebacondarwin**
The name of the worker was not included in the wrangler.toml.
Now it is added if the user specfies one at the command line, otherwise it is inferred from the current directory name.

### CODE REVIEW

**Comment by threepointone** [comment]
This was a conscious decision; a name _shouldn't_ be necessary in a `wrangler.toml` file. It could be used to develop or publish multiple workers. Its presence is necessary when publishing, but that could be passed on a per case basis with `--name <name>` CLI arg. 

The one case this makes things a little harder, is when doing `wrangler dev` with durable objects, but that's something to be fixed on the edge worker side, not on the wrangler side. 

Was there a case you bumped into that required a `name` in `wrangler.toml`?

**Comment by petebacondarwin** [comment]
Doh! I misunderstood our conversation from before, when we were talking about the init command. I thought this was a missing feature 😄. I didn't have a personal need to add this. Sorry for the noise.

**Comment by petebacondarwin** [comment]
> Its presence is necessary when publishing

Should a name in `wrangler.toml` be deprecated then?

**Comment by petebacondarwin** [comment]
Alternatively, we could keep this functionality but change it to a "default worker name" option that is used as a fallback when publishing without a specific name?

**Comment by threepointone** [comment]
We should discuss this in some more detail tomorrow, I need to wave my hands around to describe the nuance haha. Right now, in dev it generates a name (and that could be better, it just uses the file name iirc). It requires a name for durable objects so it can do a preview mode on it (there's some annoying nuance here that I'll explain later, and has to be fixed internally). For publish, we demand a name. We _could_ autogenerate it, but that's scary because it could overwrite something previously used (if the logic isn't smart enough). We definitely can make this whole thing better, let's talk about it tomorrow.

**Comment by petebacondarwin** [comment]
Hmm, I notice that there is a "name" used in KV namespaces. It is either taken from the wrangler.toml or defaults to "worker". E.g.

```
wrangler kv:namespace create SomeNamespace
```

results in a namespace with the name `worker_SomeNamespace`.

**Comment by threepointone** [comment]
yeah... https://github.com/cloudflare/wrangler2/blob/973b8f2dd93a1d5976e650fa5228bf605dd9326d/packages/wrangler/src/index.tsx#L1123-L1127 we can revisit this, let's chat about it tomorrow

**Pull request closed without merging**
