### PR TITLE
Set "upstream" miniflare option for dev --local

### LINKED ISSUE #1196: 🐛 BUG: dev --local fails when Worker fetches origin
### What version of `Wrangler` are you using?

2.0.8

### What operating system are you using?

Mac

### Describe the Bug

The following simple Worker works without --local but recurses with --local. 

```ts
export interface Env {}

export default {
  async fetch(
    request: Request,
    _env: Env,
    _ctx: ExecutionContext
  ): Promise<Response> {
    return await fetch(request.url)
  }
}
```

Running `wrangler dev` will work and correctly fetch from the origin server. Running this with `--local` will fail. On failure, Miniflare suggests setting the option `upstream` in its config, but there is no way to do that using either CLI options or changing the TOML as the 'miniflare' TOML option is deprecated and ignored.

### PR DESCRIPTION
**Pull request by sbquinlan**
Fixes #1196 

This defaults the "upstream" option of miniflare (URL to use for requests against origin) to dev.host or route using the same logic that is used to find the zone for non-local dev runs. Also added is an command option to override this default.

Included some tests and manually tested by running a worker locally.

### CODE REVIEW

**Comment by threepointone** [comment]
Thank you very much for this PR! We'll review it this week. Could you add a changeset ([instructions](https://github.com/cloudflare/wrangler2/blob/main/CONTRIBUTING.md#changesets)), and rebase and pass CI checks in the meanwhile? Thank you!

**Comment by petebacondarwin** [comment]
Related issue on Miniflare: https://github.com/cloudflare/miniflare/issues/282

**Comment by threepointone** [comment]
I was trying to rebase this PR land it, but I accidentally ended up pushing to main 🙃 It looked great, I was going to approve it and ship it anyway. I've also made sure your commits stayed signed by you, and given you credit in the changeset. Closing this PR and connected issue, thank you so very much for your contribution @sbquinlan!

**Comment by sbquinlan** [comment]
haha thanks @threepointone!

**Pull request closed without merging**
