### PR TITLE
Remix integration test

### PR DESCRIPTION
**Pull request by GregBrimble**

### CODE REVIEW

**Review by GregBrimble — COMMENTED** [review]
👍 Approve your changes @petebacondarwin

**Review by petebacondarwin — APPROVED** [review]

**Comment by threepointone** [comment]
The test appears to be failing in main, but not failing the jest process. expected? 
image

**Comment by petebacondarwin** [comment]
@threepointone - is the question why is this failing? Or why is it not failing the jest process?

I think the failure could be caused by not building wrangler beforehand?

**Comment by threepointone** [comment]
No, the test fails even if I've built wrangler. Do you not see this on your machine? 

>  is the question why is this failing? Or why is it not failing the jest process?

Both, I suppose? just curious why I'm seeing a failing test, and it's not failing CI haha.

**Comment by petebacondarwin** [comment]
It is passing on `main` on my machine... Did you `npm i` to get the latest `xxhash` package?

**Comment by threepointone** [comment]
I had done a fresh install, but ugh, I tried again,  and now it's not failing anymore lmao. Computers... 

Have a good weekend!

**Pull request merged**
