### PR TITLE
chore: setup releases for GA

### PR DESCRIPTION
**Pull request by threepointone**
This modifies how we do releases -
- The changesets flow will now publish to latest
- Every commit will now be published as beta instead of alpha

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Let's do this.

**Comment by threepointone** [comment]
merging this tomorrow, and we'll try to do a proper release too

**Comment by threepointone** [comment]
fuck it, landing this. let's see what happens.

**Comment by threepointone** [comment]
wait no I'll do it later tonight

**Pull request merged**
