### PR TITLE
fix: try bump esbuild to 0.15.0

### PR DESCRIPTION
**Pull request by rozenmd**
Making this PR to see if build even passes

resolves https://github.com/cloudflare/wrangler2/pull/1971

### CODE REVIEW

**Review by GregBrimble — APPROVED** [review]

**Comment by JacobMGEvans** [comment]
Oh interesting. Should manually test it but thats exciting

**Comment by JacobMGEvans** [comment]
> Yeah don't merge this, I don't trust it

GitHub: All of CI Passing
Our Team: 🤨

**Comment by rozenmd** [comment]
Lol @JacobMGEvans I mean, every other person that has tried to bump this had CI explode, and I do it, and it works? sus

**Comment by JacobMGEvans** [comment]
> Lol @JacobMGEvans I mean, every other person that has tried to bump this had CI explode, and I do it, and it works? sus

@rozenmd I'm working on wrapping up that templates PR it will give us more to run a battery of E2E tests against hopefully giving us more realistic results for things like this 😆😁

**Comment by rozenmd** [comment]
Tested `wrangler dev` and `wrangler publish` with esbuild 0.15.0, works well - @GregBrimble / @WalshyDev can I assume the fixtures would catch any breaking changes on the pages side?

**Comment by GregBrimble** [comment]
You may, yes

**Pull request merged**
