### PR TITLE
refactor: switch to tab indentation rather than spaces

### LINKED ISSUE #1298: Switch to hard tabs for indentation
Everyone has their own opinions about how much visual indentation they want in their code. Some prefer 2 spaces, some prefer 4, and then some users may be visually impaired and need higher font sizes with smaller tab widths, etc.

There's been a tonne of debate over the years about which is better, and it's always come to down to arguments that are opinion based, but the one major and consequential difference between the two is this:

**Tabs allow individuals in the same codebase to select their indentation widths across every tool.**

To affirm the accessibility issue, I'd recommend reading through https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/:

> coworkers who unfortunately are highly visually impaired, and each has a different visual impairment:
> 
> * one of them uses tab-width 1 because he uses such a gigantic font-size
> * the other uses tab-width 8 and a really wide monitor
> * these guys have serious problems using codebases with spaces, they have to convert, do their work, and then unconvert before committing

Other references:

- https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/
- https://alexandersandberg.com/tabs-for-accessibility/
- https://adamtuttle.codes/blog/2021/tabs-vs-spaces-its-an-accessibility-issue/

Prettier is likely to switch to `useTabs` by default with the next major version too, for this exact reason: https://github.com/prettier/prettier/issues/7475

Other than the obvious code change differences, shipping an [`.editorconfig`](https://editorconfig.org/) in this repo for some sensible defaults would probably be a good idea too, to combat one of the most common counters to this, which is how some tools render tabs by default. This way, tools like GitHub can render tabs with a 4 character width by default instead of the usual 8, but folks can still customise this themselves if they so choose. Something like this:
```
# http://editorconfig.org
root = true

[*]
indent_style = tab
tab_width = 4
```

I'd like to avoid any debate around personal preference here and focus on the accessibility issue of continuing to indent code with spaces. This discussion should probably be had for most of Cloudflare's JS/TS projects, but since wrangler is one of the biggest, I figured it best to start here.

### PR DESCRIPTION
**Pull request by petebacondarwin**
Fixes #1298

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Sadly Prettier and eslint are not playing nicely together here...

For example this code:

```ts
export async function getUserInfo(): Promise<UserInfo | undefined> {
	const apiToken = getAPIToken();
	const apiTokenFromEnv = getCloudflareAPITokenFromEnv();
	return apiToken
		? {
				apiToken,
				authType: apiTokenFromEnv ? "API" : "OAuth",
				email: await getEmail(),
				accounts: await getAccounts(),
		  }
		: undefined;
}
```

Note that the line before the `: undefined` has two tabs followed by two spaces. The spaces are there to aline the `}` with its corresponding `{`.

But eslint doesn't like this

**Comment by Cherry** [comment]
If you add `"no-mixed-spaces-and-tabs": ["error", "smart-tabs"]` to the ESLint rules, that should resolve that. `smart-tabs`  allows mixed tabs and spaces when the spaces are used for alignment. 👍

**Comment by Cherry** [comment]
I'd also recommend adding an `.editorconfig` to the root with something like this, for reasonable 4 char width defaults:
```
# https://editorconfig.org
root = true

[*]
end_of_line = lf
indent_style = tab
tab_width = 4
```

That way, you avoid the default 8 spacing GitHub uses:
Example code with 8 character tab width

And instead see this:
Example code with 4 character tab width

**Comment by petebacondarwin** [comment]
Thanks for the tips @Cherry! We currently default to 2 spaces for indentation. But otherwise I have implemented your suggestions.

**Comment by petebacondarwin** [comment]
Now the tricky dance of landing this without breaking too many other PRs :-D

**Review by threepointone — APPROVED** [review]

**Pull request merged**
