### PR TITLE
fix: check for nonempty kv id and r2 bucket_name

### LINKED ISSUE #1660: 🐛 BUG: KV & R2 bindings with a empty string ID/name are rejected by the API rather than being caught by config validation
### What version of `Wrangler` are you using?

2.0.24

### What operating system are you using?

Mac

### Describe the Bug

Bindings with a blank identifier, such as `id = ""` or `bucket_name = ""` for `kv_namespaces` and `r2_buckets` respectively, throw a `workers.api.error.internal_server` error as opposed to being caught by config validation in wrangler.

I assume this is since the validation checks for a string, but not if that string has any content.

https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/config/validation.ts#L1633

## Example configuration

```toml
[[kv_namespaces]]
binding = "foo"
id = ""

[[r2_buckets]]
binding = "bar"
bucket_name = ""
```

## Error returned

```
Your worker has access to the following bindings:
- KV Namespaces:
  - foo: 
- R2 Buckets:
  - bar: 
Total Upload: 0.29 KiB / gzip: 0.20 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/134a5a2c0ba47b38eada4b9c8ead10b6/workers/scripts/test-worker) failed.

  workers.api.error.internal_server [code: 10002]
```

### PR DESCRIPTION
**Pull request by arjunyel**
Close #1660

In `packages/wrangler/src/config/validation.ts` I originally tried to get `isRequiredProperty` to type narrow `object`. This may be impossible https://github.com/microsoft/TypeScript/issues/31755#issuecomment-498669080 so I casted it manually.

### CODE REVIEW

**Comment by arjunyel** [comment]
Sorry, not sure why my VS Code didn't run Prettier, fixed

**Comment by Skye-31** [comment]
This is missing a changeset by the way (run `npx changeset` in your terminal to create one)

**Comment by arjunyel** [comment]
Hello I can generate a changeset tonight, just curious what changes need one? The API always rejected empty strings so this didn't seem like a change a user would notice. Thank you!

**Review by threepointone — APPROVED** [review]

**Comment by threepointone** [comment]
Looks good to me. Thank you for the PR!

**Pull request merged**
