### PR TITLE
feat: implement `[text_blobs]`

### PR DESCRIPTION
**Pull request by threepointone**
This implements support for `[text_blobs]` as defined by https://github.com/cloudflare/wrangler/pull/1677.

Text blobs can be defined in service-worker format with configuration in `wrangler.toml` as -

```
[text_blobs]
MYTEXT = "./path/to/my-text.file"
```

The content of the file will then be available as the global `MYTEXT` inside your code. Note that this ONLY makes sense in service-worker format workers (for now).

Workers Sites now uses `[text_blobs]` internally. Previously, we were inlining the asset manifest into the worker itself, but we now attach the asset manifest to the uploaded worker. I also added an additional example of Workers Sites with a modules format worker.

Closes https://github.com/cloudflare/wrangler2/issues/412

### CODE REVIEW

**Comment by threepointone** [comment]
The code for these codepaths isn't too hairy at the moment, but is starting to look a bit verbose. I'll try to do a cleanup when I implement `[build.upload.rules]`.

**Comment by threepointone** [comment]
Weird test failure, I'll look into it in a bit.

**Comment by petebacondarwin** [comment]
I think it is actually a flake. I saw something like this before. I have re-run the jobs...

**Comment by threepointone** [comment]
I re-ran this 3 times and it's still failing. Extremely annoying. Not even sure how to start resolving this, but I'll think about it...

**Comment by threepointone** [comment]
(But don't let that stop you from reviewing!)

**Comment by threepointone** [comment]
Ok, for some reason, moving the `[wasm_modules]` tests before the `[text_blobs]` tests made it pass on windows. 🤷‍♂️

**Comment by petebacondarwin** [comment]
> Ok, for some reason, moving the [wasm_modules] tests before the [text_blobs] tests made it pass on windows. 🤷‍♂️

That is not a good sign. It means that we are leaking state between these tests...

**Review by petebacondarwin — APPROVED** [review]
LGTM.

**Pull request merged**
