### PR TITLE
Fix network tab in DevTools inspector

### LINKED ISSUE #63: Fix network tab in DevTools
The runtime supports the Network tab, but for some reason, it does not work. For instance, it works on https://cloudflareworkers.com

### PR DESCRIPTION
**Pull request by Electroid**
Fixes #63 

Screen Shot 2021-11-30 at 6 03 18 PM

### CODE REVIEW

**Comment by Electroid** [comment]
Known issues:
* Network requests only appear after the 2nd request. This is a runtime issue, which we'll track elsewhere.
* Dark mode does not work. This is because we have an internal fork of the DevTools UI that is outdated. We need to rebase it, then open source it in this monorepo.

**Comment by threepointone** [comment]
why not use built-pages here? I have modifications that lets it restart on updates/watch mode. does it not work with your changes? You'd also mentioned that the devtools on cloudflareworkers have bugs.

**Review by threepointone — CHANGES_REQUESTED** [review]
^ questions.

**Comment by Electroid** [comment]
The network tab only works with this version— likely because we have some custom extensions to the protocol.

We should figure out how to merge these changes together, I’m sure there are other improvements we could make the the UI.

**Comment by threepointone** [comment]
Please point me to that fork so I can bring those changes in. I can't merge this PR because the refresh-on-change would go away.

**Comment by Electroid** [comment]
We're going to defer this until we combine these 2 forks.

**Pull request closed without merging**
