### PR TITLE
refactor: use esbuild "file" loaders to add runtime files to the published assets

### PR DESCRIPTION
**Pull request by petebacondarwin**

### CODE REVIEW

**Review by threepointone — CHANGES_REQUESTED** [review]
The reasoning is good, but I don't like the implementation of using `require` to instead inline the path to the file. It's confusing if you read it and you don't know what's going on. Instead, I recommend making a new virtual module (say, `wrangler-template-paths`) that exports an object to these paths. 

```ts
import paths from 'wrangler-template-paths';
paths['new-worker.template.js']; // /asbolute/path/to/new-worker.template.js
// etc
```

Implementing this would be an esbuild plugin that captures imports to `wrangler-template-paths` and sends an object with those paths as its content. What do you think?

**Comment by petebacondarwin** [comment]
Is your concern the use of `require()` rather than `import`? Or the fact that these are dotted around the codebase?

**Comment by threepointone** [comment]
The concern us around using `require`, but I'd feel this way about using `import` as well. It's extremely curious to see a require/import of a ts/json file result in a string path to that file. file loaders are typically used for static assets, and even that is a bit icky, but is a better option until we have import assertion attribute evaluators (or any other standard that passes). But using it for .ts/.json files feels a bit wrong. More concernedly, it'll be confusing for anyone who comes by it in the future and doesn't understand what it's doing. 

Here's another alternative - 
```
pathToTemplateFile('new-worker.ts'); // where `pathToTemplate` is a magic global function that works in our codebase

```
^ If this would desugar to a `require()` that uses a file loader to do the same thing you mentioned, (using `define` in the esbuild config) I would feel much better about it, since it's a little more obvious what's going on.

**Review by JacobMGEvans — APPROVED** [review]
This is a great improvement not just on pathing but how we bundle files we need i.e. templates 

If it is not already done I will close the PR that I started to initially handle the pathing for `pages` template, this PR handles that and more! 

Edit: Provisional to Greg's approval as well as resolution in conversation pertaining to functional [abstraction `pathToTemplate`](https://github.com/cloudflare/wrangler2/pull/860#issuecomment-1114631021)

**Comment by petebacondarwin** [comment]
This PR is very stale and not likely to land soon as it has limited impact and requires more discussion.

**Pull request closed without merging**
