### PR TITLE
Fix incorrect extension extraction from file paths

### LINKED ISSUE #1029: 🐛 BUG: Issue uploading a file without an extension to a Pages project
## What version of Wrangler are you using?
2.0.5

## What operating system are you using?
Windows

## Describe the Bug
When performing a direct upload for a Pages project using the following command `npx wrangler pages publish build --project-name=RANDOMPROJECT` it fails if it encounters a file without an extension like `.well-known/apple-app-site-association`.

I can get the same file into a Page project using git and pushing to a branch, but direct upload fails.

image

### PR DESCRIPTION
**Pull request by jrf0110**
Fixes #1029

Our extension extraction logic was taking into account folder names, which can include periods. The logic would incorrectly identify a file path of `.well-known/foo` as having the extension of `well-known/foo` when in reality it should be an empty string.

### CODE REVIEW

**Review by threepointone — COMMENTED** [review]
Looks good to me. Would you like to add a test for this?

**Review by threepointone — APPROVED** [review]
I'm happy to stamp this, but would you also like to add a changeset for this? Run `npx changeset` at the root, choose wrangler / patch, and the content can be exactly the title + description of this PR.

**Review by GregBrimble — APPROVED** [review]
Thanks @jrf0110 , appreciate ya!

**Review by petebacondarwin — APPROVED** [review]
LGTM

**Pull request merged**
