### PR TITLE
Support Cloudflare Access for `wrangler dev`

### PR DESCRIPTION
**Pull request by penalosa**
Enable support for `wrangler dev` on Workers behind Cloudflare Access, utilising `cloudflared`. If you don't have `cloudflared` installed, Wrangler will prompt you to install it. If you _do_, then the first time you start developing using `wrangler dev` your default browser will open with a Cloudflare Access prompt.

### CODE REVIEW

**Review by Twitter1268 — APPROVED** [review]

**Comment by JacobMGEvans** [comment]
Very interested in getting this in, is there any particular reason there is no testing around it?

**Review by JacobMGEvans — CHANGES_REQUESTED** [review]
Very interested in getting this in, is there any particular reason there is no testing around it?

**Comment by penalosa** [comment]
I'm not entirely sure how this could be tested in an automated way. It requires a domain set up for Access, as well as `cloudflared` installed.

**Comment by JacobMGEvans** [comment]
> I'm not entirely sure how this could be tested in an automated way. It requires a domain set up for Access, as well as `cloudflared` installed.

Hmmmm, I don't know how I feel pushing this up without testing. We may need to think about a minimal testing for the code (implementation details) or behavior.

**Comment by penalosa** [comment]
@JacobMGEvans I've added a couple unit tests

**Comment by JacobMGEvans** [comment]
> @JacobMGEvans I've added a couple unit tests

I appreciate the effort in figuring out a way to test this!

**Review by JacobMGEvans — APPROVED** [review]

**Pull request merged**
