### PR TITLE
feat: wasm support for local mode in `wrangler dev`

### PR DESCRIPTION
**Pull request by threepointone**
This adds support for `*.wasm` modules into local mode for `wrangler dev`.

In 'edge' mode, we create a javascript bundle, but wasm modulesare uploaded to the preview server directly when making the worker definition form upload. However, in 'local' mode, we need to have the actual modules available to the bundle. So we copy the files over to the bundle path. We also pass appropriate `--modules-rule` directive to `miniflare`.

I also added a sample wasm app to use for testing, created from a default `workers-rs` project.

Fixes https://github.com/cloudflare/wrangler2/issues/299

### CODE REVIEW

**Comment by threepointone** [comment]
I'm having tgrouble getting this to actually work. When I try to test it (with `npm start -- dev ../example-wasm-app/worker/shim.mjs --local`), I get this error from miniflare 

```
[mf:err] RangeError: path should be a `path.relative()`d string, but got "../../../../../../var/folders/cq/w4qlzy2d4v924d23r3yj7pk00000gn/T/tmp-56461-QyfpfeThMdQh/2c06325b9d33bc9dbfad457a527e90cbcae55751-index_bg.wasm"
    at throwError (/Users/threepointone/code/nu-wrangler/node_modules/ignore/index.js:364:9)
    at checkPath (/Users/threepointone/code/nu-wrangler/node_modules/ignore/index.js:383:12)
    ...
```

This points to this code https://github.com/cloudflare/miniflare/blob/ab60cad387d5266e73d4c93e44ab4fa57aec1e36/packages/runner-vm/src/linker.ts#L92-L96

This appears to be an error from the `ignores` package, but it's confusing because the path provided _is_ relative. I'll investigate some more later.

//cc @mrbbot, if you have any ideas. No rush!

**Comment by threepointone** [comment]
Aight, I think this is ready for review.

**Review by petebacondarwin — APPROVED** [review]
Looks good as far as I can tell.
I tried running the `example-wasm-app` locally and it didn't crash... so that's good.

**Comment by threepointone** [comment]
Thank you for actually trying it out! I do appreciate that.

**Pull request merged**
