### PR TITLE
docs: outline/stubs

### PR DESCRIPTION
**Pull request by threepointone**
This makes a folder for docs, with outlines for some pages that should probably exist. There's no real content just yet, but this could lay a foundation and a skeleton structure.

### CODE REVIEW

**Comment by threepointone** [comment]
cc @lauragift21

(@jgentes please add Gift to the wrangler team https://github.com/orgs/cloudflare/teams/wrangler thank you!)

**Comment by threepointone** [comment]
Does this look like a reasonable outline to the two of you? I figured I'd work on the v1v2 doc myself (ignore the bullets I'd put, I'll make it nicer). Any suggestions?

**Comment by lauragift21** [comment]
> Does this look like a reasonable outline to the two of you? I figured I'd work on the v1v2 doc myself (ignore the bullets I'd put, I'll make it nicer). Any suggestions?

I like the overall structure! Thank you for laying out the pages. @jkup and I can start working out the getting started guide.

Question: Is there also going to be a migration guide separate from the v1v2 doc you're working on now?

**Comment by threepointone** [comment]
Oh good point, yes we should definitely have a separate migration guide.

**Comment by jkup** [comment]
This looks great to me! Should we merge this in so @lauragift21 and I can start filling in some of the pages?

**Comment by threepointone** [comment]
Lemme remove my bullets from the v1v2 thing and add a stub for a migrations doc and I'll merge it in 

But of course, feel free to make changes

**Comment by threepointone** [comment]
Done and done. Lemme know how else I can help.

**Pull request merged**
