### PR TITLE
fix: kv:key put upload binary files fix

### LINKED ISSUE #1254: 🐛 BUG: kv:key put no longer able to upload binary files
### What version of `Wrangler` are you using?

2.0.8

### What operating system are you using?

Mac

### Describe the Bug

We've just upgraded from wrangler 1 -> 2. We were using `wrangler kv:key put` to upload images into KV from CLI. It seems in wrangler 2 those images get mangled when uploading.

I believe it is related to this line and the fact that values are always passed as strings...
https://github.com/cloudflare/wrangler2/blob/e3ce82b0cbb5e5765fa09ab3322b42a5b75934e3/packages/wrangler/src/index.tsx#L2262-L2265

### PR DESCRIPTION
**Pull request by f5io**
fixes #1254

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Thank you for putting this together so quickly.
Please could you add a unit test after 
https://github.com/cloudflare/wrangler2/blob/de4e3c2d4a0b647f190e709a0cadb6ef8eb08530/packages/wrangler/src/__tests__/kv.test.ts#L450-L464

And also can you run `npx changeset` to add a changeset for this fix.

**Comment by f5io** [comment]
@petebacondarwin as requested, all done...

i had to slightly change the older test as all files are now just handled as straight Buffers, hope that's not a problem. full jest suite passed on my machine

**Comment by JacobMGEvans** [comment]
This is looking great! I will leave it up to @petebacondarwin for the approval 😄

**Review by petebacondarwin — APPROVED** [review]
Love it! Thanks @f5io and well done for ramping up to our development flow so quickly and effectively.

**Comment by threepointone** [comment]
We have to revert this because of this issue https://github.com/cloudflare/wrangler2/issues/1273 We'll work on a fix (unless @f5io a fix comes to mind for you?) and release it right after

**Comment by f5io** [comment]
i can have a look at this today.

**Comment by threepointone** [comment]
Potentially also wrangler2 older versions and wrangler2 newer versions iiuc 

I'd like to make sure we have a proper story for all combinations before we roll this out, just being cautious

**Comment by f5io** [comment]
i believe the new issue relates to just logging the output of getKVKeyValue, if there's some way we can dump this to stdout

**Pull request merged**
