### PR TITLE
chore: refactor docs command

### PR DESCRIPTION
**Pull request by rozenmd**
Refactor to allow folks to enter a command to "search" for - I intend to hook this up to a search index later - don't worry too much about the hardcoded command strings

### CODE REVIEW

**Comment by penalosa** [comment]
Does this definitely need to be a new command? It seems, given it takes a command, that this might work better as a flag for the `help` command (`wrangler help kv --browser`, maybe)

**Comment by rozenmd** [comment]
Maybe, but that's not the UX I'm going for here

After this PR, the command will work like this:
`wrangler docs` -> open the docs
`wrangler docs <command>` -> open the docs to the part of the docs you want

Once I get access to DocSearch, I can delete all the command code, and in a future PR it'll be:
`wrangler docs` -> open the docs
`wrangler docs <search term>` -> show the top N results in a list, hitting enter opens your browser to that result

**Comment by rozenmd** [comment]
@penalosa out of curiosity, why *not* a new command?

**Comment by rozenmd** [comment]
> @rozenmd this takes care of #2359 right?
> 
> Personally, I'm ok with `wrangler docs` and subsequent addition to go to a specific place in the docs. I think it's a better experience (and more discoverable) than nesting it under existing commands.
> 
> Is there an issue in the docs repo to add the new command?

yeah it takes care of #2359 - I haven't made an issue in the docs repo as all of the work should be doable in this repo

or do you mean documenting the docs command?

**Review by JacobMGEvans — APPROVED** [review]
This is an awesome DX improvement on the command

**Pull request merged**
