### PR TITLE
add @rozenmd to CODEOWNERS

### PR DESCRIPTION
**Pull request by rozenmd**
Just me volunteering to get pinged on every PR

### CODE REVIEW

**Review by penalosa — APPROVED** [review]
✅

What about adding @cloudflare/devprod, as well?

**Comment by penalosa** [comment]
Oh wait that's not a team-do we have a team on GitHub?
cc @lrapoport-cf

**Comment by lrapoport-cf** [comment]
@penalosa there's a wrangler-admins team if you want to use that instead 👍

**Comment by JacobMGEvans** [comment]
> @penalosa there's a wrangler-admins team if you want to use that instead 👍

Probably should be this or have the team on it.

**Pull request merged**
