### PR TITLE
fix: Fallback to non-interactive mode on error

### LINKED ISSUE #1303: 🐛 BUG: Can't pipe to `wrangler secret put`
### What version of `Wrangler` are you using?

2.0.7 and 2.0.14

### What operating system are you using?

Windows and Ubuntu 22.04 on WSL

### Describe the Bug

When trying to pipe data from a file to `wrangler secret put` using `cat secret.txt | wrangler secret put SECRET`, wrangler returns an error from [vadimdemedes/ink](https://github.com/vadimdemedes/ink) with the following text:
```
Error: Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.
Read about how to prevent this error on https://github.com/vadimdemedes/ink/#israwmodesupported
    at App.handleSetRawMode (C:\Users\william\AppData\Roaming\nvm\v18.0.0\node_modules\wrangler\wrangler-dist\cli.js:70355:21)
    at C:\Users\william\AppData\Roaming\nvm\v18.0.0\node_modules\wrangler\wrangler-dist\cli.js:70992:9
    at jh (C:\Users\william\AppData\Roaming\nvm\v18.0.0\node_modules\wrangler\wrangler-dist\cli.js:19869:26)
    at exports2.unstable_runWithPriority (C:\Users\william\AppData\Roaming\nvm\v18.0.0\node_modules\wrangler\wrangler-dist\cli.js:16051:16)
    at Pc (C:\Users\william\AppData\Roaming\nvm\v18.0.0\node_modules\wrangler\wrangler-dist\cli.js:16666:16)
    at Qg (C:\Users\william\AppData\Roaming\nvm\v18.0.0\node_modules\wrangler\wrangler-dist\cli.js:19821:18)
    at C:\Users\william\AppData\Roaming\nvm\v18.0.0\node_modules\wrangler\wrangler-dist\cli.js:19811:13
    at V (C:\Users\william\AppData\Roaming\nvm\v18.0.0\node_modules\wrangler\wrangler-dist\cli.js:15977:22)
    at Timeout.w [as _onTimeout] (C:\Users\william\AppData\Roaming\nvm\v18.0.0\node_modules\wrangler\wrangler-dist\cli.js:15818:13)
    at listOnTimeout (node:internal/timers:564:17)
```

I am able to reproduce this under Windows and Ubuntu 22.04 on WSL in both Wrangler 2.0.7 and Wrangler 2.0.14, in addition to other users in past issues.

### PR DESCRIPTION
**Pull request by wgyt**
If the terminal isn't a TTY, fallback to non-interactive mode instead of throwing an error. This makes it so users of Bash on Windows can pipe to wrangler without an error being thrown.

resolves #1303

hopefully I did this right...

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Thanks for sending in this PR @wgyt.
Please can you fix the formatting. Simplest way is to run (in the root of the project): `npm run fix`.

Then I would like to see if we can add a test in for this.
Perhaps in `user.test.ts` we could add a test that replacess `stdout.isTTY` with a getter that throws an error?

**Comment by wgyt** [comment]
> Thanks for sending in this PR @wgyt. Please can you fix the formatting. Simplest way is to run (in the root of the project): `npm run fix`.

Sure, I'll fix that.

> Then I would like to see if we can add a test in for this. Perhaps in `user.test.ts` we could add a test that replacess `stdout.isTTY` with a getter that throws an error?

I'll try to see if I can implement that in a test, might require us to `isInteractive` from `user.tsx` though.

**Comment by petebacondarwin** [comment]
Thanks for the updates @wgyt - I don't think the test was quite what we needed.
I added a further commit, which is what I had envisaged; it turned out to be quite fiddly to get the `isTTY` property to throw an error.
If the CI goes green then I think we should merge this PR. I'll see if I can get another team member to do a review too.

**Comment by wgyt** [comment]
> Thanks for the updates @wgyt - I don't think the test was quite what we needed. I added a further commit, which is what I had envisaged; it turned out to be quite fiddly to get the `isTTY` property to throw an error. If the CI goes green then I think we should merge this PR. I'll see if I can get another team member to do a review too.

Cool, I wasn't quite sure how to do the test in the first place, but the test you've added seems to act a lot more like the scenario that I was experiencing the issues in the first place.

**Review by petebacondarwin — APPROVED** [review]
Approving but waiting on another review since I added to this PR.

**Review by JacobMGEvans — APPROVED** [review]
LGTM

**Pull request merged**
