### PR TITLE
Use inherited config in `publish`

### PR DESCRIPTION
**Pull request by skirsten**
I found that the env specific overwrite did not work for `workers_dev`.
Also fixed some others.

### CODE REVIEW

**Comment by petebacondarwin** [comment]
This looks great. Thanks @skirsten 
Do you think you might be able to add some tests to publish.test.ts in order to prove the fix?

**Comment by skirsten** [comment]
I added some tests.
Not sure about test 2 and 3 as they just test if the inheritance of the config works...

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Excellent tests thank you!
Two more would be really helpful, which would test if `--compatibility-date` was used at the command line to override the value in wrangler.toml.
Also could you add a changeset? Run `npx changeset` and select a patch change to the wrangler package.

**Review by petebacondarwin — APPROVED** [review]
Awesome! Thanks @skirsten.

**Pull request merged**
