### PR TITLE
wrangler tail tty-awareness and json-respecting

### LINKED ISSUE #493: feature request: `wrangler tail` non-TTY behaviour
Following on from https://github.com/cloudflare/wrangler2/issues/5#issuecomment-998499017

- if non-TTY do not display informational messages, and default to JSON format
- if TTY then display informational message, and default to pretty format

### PR DESCRIPTION
**Pull request by caass**
Make `wrangler tail` TTY-aware, and stop printing non-JSON in JSON mode

Closes #493

2 quick fixes:

- Check `process.stdout.isTTY` at runtime to determine whether to default to "pretty" or "json" output for tailing.
- Only print messages like "Connected to {worker}" if in "pretty" mode (errors still throw strings)

### CODE REVIEW

**Review by threepointone — APPROVED** [review]
🍞🥖🥐🥯🥨🥪🫓

**Comment by threepointone** [comment]
well, after the tests pass ofc

**Comment by caass** [comment]
> well, after the tests pass ofc

aurghhhh they pass on my machine wtf

**Comment by threepointone** [comment]
CI is not a TTY, maybe that's it?

**Pull request merged**
