### PR TITLE
feat:  working directory pathing

### LINKED ISSUE #1243: 🐛 BUG: `--site` should resolve relative to cwd, not wrangler.toml
### What version of `Wrangler` are you using?

2.0.9

### What operating system are you using?

Mac

### Describe the Bug

Because of this code 
https://github.com/cloudflare/wrangler2/blob/f8a21ede2034f921b978e4480fe2e6157953a308/packages/wrangler/src/sites.tsx#L283-L285

We resolve the Site directory relative to the location of `wrangler.toml`. We probably shouldn't do that when the bucket is passed via `--site` (as opposed to `config.site.bucket`), it should resolve relative to process.cwd().

### PR DESCRIPTION
**Pull request by JacobMGEvans**
Before we were resolving the Site directory relative to the location of  at all times.
Now the  is resolved relative to current working directory. Additionally, we added logging of where
the configuration is being read from.

resolves #1243

### CODE REVIEW

**Comment by petebacondarwin** [comment]
The logging was because of this comment in the original issue:

> Additionally we should log to terminal Reading configuration from relative/path/to/wrangler.toml...

**Comment by JacobMGEvans** [comment]
> That's weird, I didn't put that in the issue, but I did say it in chat...
> 
> @rozenmd did you copy paste that into the issue?
> 
> Anyway, the logging should happen inside readConfig, not in this function. We can bikeshed whether it should be .debug or .log

I'll pick that up whenever we have it "ready for development"

**Comment by JacobMGEvans** [comment]
Removed the logging logic for later issue/PR

**Review by threepointone — APPROVED** [review]
looks good, one suggestion!

**Comment by threepointone** [comment]
well, 3 suggestions :P

**Comment by threepointone** [comment]
Would you like to send a similar PR for --assets?

**Comment by JacobMGEvans** [comment]
> Would you like to send a similar PR for --assets?

Yeah totally 😄

**Comment by JacobMGEvans** [comment]
> > Would you like to send a similar PR for --assets?
> 
> Yeah totally 😄

Created moved to in-progress #1333

**Pull request merged**
