### PR TITLE
Launch server as localhost instead of 127.0.0.1

### PR DESCRIPTION
**Pull request by jacobPARIS**
Unless there's any strong reason to prefer the IP address over `localhost` that I'm not privy to, I'd like to propose changing wrangler to announce the server starting as localhost instead

Browsers can't set cookies to IP addresses, so any login or session tracking that a project might want to do won't work until the user switches to localhost, which can be the cause for some confusion if the dev isn't already familiar with that behaviour.

### CODE REVIEW

**Comment by petebacondarwin** [comment]
I had this vague recollection from previous projects that there is something better about using one or the other. But I can't, for the life of me, remember what it was...
A quick Google (and StackOverflow search) turned up this comment:

https://stackoverflow.com/questions/7382602/what-is-the-difference-between-127-0-0-1-and-localhost#comment116497184_7382631

> On my Windows10 system the DNS lookup is really, really slow, about 1100 milli secs. So I switched to 127.0.0.1 – 
Wolfgang Kuehn Jan 25 '21 at 17:26

But I have not tested that theory.

**Comment by justinnoel** [comment]
One advantage to an IP address is that it can be loaded by devices on your network.

I always prefer the server start at `0.0.0.0`. That way, it can be served from `localhost` as well as your actual IP address.

**Comment by justinnoel** [comment]
> One advantage to an IP address is that it can be loaded by devices on your network.

Of course Cloudflare Tunnel can solve this as well.

**Comment by GregBrimble** [comment]
> Browsers can't set cookies to IP addresses, so any login or session tracking that a project might want to do won't work until the user switches to localhost, which can be the cause for some confusion if the dev isn't already familiar with that behaviour.

@JacobParis , I'm not sure this is true. I just spun up a quick test:

```js
const express = require("express");
const app = express();
const port = 3000;

app.get("/", (req, res) => {
  res.setHeader("Set-Cookie", "name=value;");
  res.send("Hello World!");
});

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`);
  console.log(`Example app listening at http://127.0.0.1:${port}`);
});
```

And cookies were sent in the response, saved by the browser, and sent on subsequent requests when visiting both `localhost` and `127.0.0.1`.

Looking further, there's maybe some quirks if people are setting a `domain` for their cookie. But for both `localhost`, and `127.0.0.1`, [I could't make that work](https://stackoverflow.com/a/1188145).

Do you have a repro of cookies not working on 127.0.0.1?

@justinnoel , I'm totally on board with changing it to `0.0.0.0`. @JacobParis , how do you feel about this instead?

**Comment by GregBrimble** [comment]
#184 raising the point that `127.0.0.1` is inaccessible over ipv6. I assume the same is true for `0.0.0.0`, (so maybe `localhost` is in fact the best option) but I haven't checked yet.

**Comment by maraisr** [comment]
Might just also add @GregBrimble it seems that ipv6 is the default network interface on M1 macs, as opposed to v4 on Intel. Can't say for fact, but starting `http` on Intel binds to 0.0.0.0, and binding M1, to ::1. Granted 100% not related, but still pointing that I may not be an edge case, and you'll find an increasing number of v6 usecases. 

On the cookie support for ips:

If you bind to an ambient ip, ::1 or 0.0.0.0 — then any inbound connection will be allowed on the network (provided there is an open firewall), every device also has a hostname, generally on Mac is just <yourname>.local. Once again depending on your network, that'll just work if you wanna visit that cross device, without the need for an ip. 

In any case, I believe there is 2 cases here. What you proxy or "upstream", and on what do start your very own local server as.

What you upstream, 100% shouldn't be automatic, and rather a `--origin=http://localhost:8080` (or something to that effect). My opinion.

As for what your own server is, that is more than okay to be 0.0.0.0, outside security issues (makes pc accessible on entire network) — is fine, as `localhost` already can forward to that. It's more just about DX, as pointed out. You can bind the server to 127.0.0.1 (to mitigate security), but all the cli links or auto browser opens to open "localhost".

**Comment by GregoireF** [comment]
Hello,

Having various local projects running with localhost or 127.0.0.1 for various reasons, I don't encounter any problems setting cookies on either set. However, as mentioned above, I think that booting on 0.0.0.0 might be the best idea?

Cheers

**Comment by GregBrimble** [comment]
Alrighty, I've just tried `localhost` on my machine. I'm able to access it:

- at `http://127.0.0.1:8788/`
- at `http://[::]:8788/`
- at `http://[::1]:8788/`
- at `http://localhost:8788/`
- at `http://0.0.0.0:8788/`
- and from another device on my LAN, at `http://<DEVICE_IPV4>:8788/`

This was done on my M1 MacBook.

So if there are no objections in the next few of days, I'll swap this over to `localhost` next week.

**Comment by GregBrimble** [comment]
Thanks everyone for all of your input. Merging this as soon as the tests pass :)

**Review by GregBrimble — APPROVED** [review]

**Pull request merged**
