### PR TITLE
feat: Add `--inspector` argument to `wrangler pages dev`

### PR DESCRIPTION
**Pull request by Skye-31**

### CODE REVIEW

**Comment by GregBrimble** [comment]
`--inspect` is deprecated on `wrangler dev`. By default, it's turned on now. I don't think we'll want to add the argument to `wrangler pages dev`.

**Comment by Skye-31** [comment]
This is to turn it off, not on! It defaults to true, like before the PR

**Comment by Skye-31** [comment]
This is to turn it off (i.e. --inspect false), not on! It defaults to true, like before the PR.

**Comment by GregBrimble** [comment]
Yeah, I don't think we want to offer a way for people to turn this off :) Is there any reason they'd need to that I'm missing?

**Comment by Skye-31** [comment]
I was considering it for the fixtures tests, they do quite a bit of spamming that it failed to listen to the port (especially in watch mode). Also helps on low-spec devices with less memory available (had it crash on my laptop a few times when there were several wrangler instances), and as devtools is pretty heavy, disabling it helped.

**Pull request closed without merging**
