### PR TITLE
add `.prettierignore`, run it on the whole codebase

### PR DESCRIPTION
**Pull request by threepointone**
This commit adds a `.prettierignore` config, and runs prettier on the whole codebase, catching some files we'd missed out on.

There's no changeset required for this commit.

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
LGTM - but perhaps add a prettier check to the CI?

**Comment by threepointone** [comment]
I thought we did (https://github.com/cloudflare/wrangler2/blob/cea27fe09b0b36439faeaec1317b16e0143cf4c4/.github/workflows/tests-typecheck.yml#L57-L59) but it's configured a little confusingly (cc @JacobMGEvans, I don't think we should use prettier via eslint here https://github.com/cloudflare/wrangler2/blob/cea27fe09b0b36439faeaec1317b16e0143cf4c4/package.json#L69, it only runs on ts/tsx files; instead we should separately run https://prettier.io/docs/en/cli.html#--check on all files)

**Comment by petebacondarwin** [comment]
> I thought we did (
> 
> https://github.com/cloudflare/wrangler2/blob/cea27fe09b0b36439faeaec1317b16e0143cf4c4/.github/workflows/tests-typecheck.yml#L57-L59
> 
> ) but it's configured a little confusingly (cc @JacobMGEvans, I don't think we should use prettier via eslint here
> https://github.com/cloudflare/wrangler2/blob/cea27fe09b0b36439faeaec1317b16e0143cf4c4/package.json#L69
> 
> , it only runs on ts/tsx files; instead we should separately run https://prettier.io/docs/en/cli.html#--check on all files)

Ah, right - I didn't spot that hidden eslint plugin :-D

**Comment by JacobMGEvans** [comment]
> I thought we did (
> 
> https://github.com/cloudflare/wrangler2/blob/cea27fe09b0b36439faeaec1317b16e0143cf4c4/.github/workflows/tests-typecheck.yml#L57-L59
> 
> ) but it's configured a little confusingly (cc @JacobMGEvans, I don't think we should use prettier via eslint here
> https://github.com/cloudflare/wrangler2/blob/cea27fe09b0b36439faeaec1317b16e0143cf4c4/package.json#L69
> 
> , it only runs on ts/tsx files; instead we should separately run https://prettier.io/docs/en/cli.html#--check on all files)

I can take care of that.

**Pull request merged**
