### PR TITLE
Remove experimental warning for dispatch namespaces

### PR DESCRIPTION
**Pull request by markjmiller**
- Remove experimental warning for dispatch namespaces since the [feature is GA](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/get-started/configuration/).
- Update `namespace` to `dispatch_namespace` in upload form (the script upload API accepts both).

Tested with [Workers for Platforms Example Project](https://github.com/cloudflare/workers-for-platforms-example).
`npm start -w wrangler publish -- --config /path/to/workers-for-platforms-example-project/wrangler.toml`

### CODE REVIEW

**Comment by rozenmd** [comment]
Thanks for the PR @markjmiller - do you mind adding a changeset? (`npx changeset`)

**Review by penalosa — CHANGES_REQUESTED** [review]
It doesn't look like this feature is documented on [the Wrangler configuration page](https://developers.cloudflare.com/workers/wrangler/configuration/)—could you open a PR to the docs repo before this gets merged?

**Comment by markjmiller** [comment]
@penalosa we have a PR ready to merge for docs, but our doc writer won't be able to merge until they get back from holiday vacation. Is that a blocker, or can we merge this now?

**Review by rozenmd — APPROVED** [review]

**Comment by rozenmd** [comment]
LGTM @markjmiller

**Comment by lrapoport-cf** [comment]
@markjmiller can you please link the associated docs PR for posterity?

**Comment by markjmiller** [comment]
https://developers.cloudflare.com/workers/wrangler/commands/#dispatch-namespace

**Pull request merged**
