### PR TITLE
Load `.env`/`.dev.vars` file based on `--env`

### LINKED ISSUE #1305: feat: `--env` + `.env`/`.dev.vars` (environment support for build/runtime vars)
We currently support [`dotenv`](https://www.npmjs.com/package/dotenv) integration in 2 ways - 
- When you make a `.env` file in your project, any values in there are available on `process.env` during custom builds. Further, you can even use this to populate values like `CLOUDFLARE_ACCOUNT_ID`, `CLOUDFLARE_API_TOKEN`, etc. 
- When you make a file called `.dev.vars`, we populate `[vars]` in _runtime_ of the Worker, i.e. when the Worker is actually running. This is useful for swapping in vars during development without having to edit `wrangler.toml`, but it's _particularly_ useful when we need to populate secrets in local mode (since it wouldn't otherwise get the values we've set in the dashboard.

Neither of these files is meant to be checked in, and the `.gitignore` we generate during `wrangler init` includes them. 

This issue is about expanding support, specifically about adding environment support. When using `--env <environment>`
- We should load `.env.<environment>` when available (and use `.env` when it isn't). imo we should not merge values of both files, but I'm not sure what the norm is here and we should probably do that. 
- Similarly for runtime, we should load `.dev.vars.<environment>` when available (and use `.dev.vars` when it isn't).

### PR DESCRIPTION
**Pull request by mrbbot**
If `--env <env>` is specified, we'll now check `.env.<env>`/`.dev.vars.<env>` first. If they don't exist, we'll fallback to `.env`/`.dev.vars`.

`--env` is now a flag in every command, like `--config`.

Closes #1305.

### CODE REVIEW

**Comment by GregBrimble** [comment]
Have you considered `.<env>.env` instead? I imagine IDEs which do `INI` style formatting will expect the file to have a `.env` extension. (I haven't actually tested this)

**Comment by petebacondarwin** [comment]
> Have you considered `.<env>.env` instead? I imagine IDEs which do `INI` style formatting will expect the file to have a `.env` extension. (I haven't actually tested this)

I think that keeping the extension constant would be sensible.

**Comment by GregBrimble** [comment]
Interesting that the new Turbopack uses `.env.<xyz>`: https://turbo.build/pack/docs/features/environment-variables#env-files

**Comment by GregBrimble** [comment]
Nah, I think I was wrong in my comment. I just assumed people would want to keep the `.env` extension, but if everyone else is going with suffixes for environments, then let's just do the same.

**Review by JacobMGEvans — APPROVED** [review]

**Review by GregBrimble — CHANGES_REQUESTED** [review]
Hold off merging just a minute until we confirm if global `--env` is what we want to do

**Pull request merged**
