### PR TITLE
Pass `usageModel` to Miniflare in local dev

### LINKED ISSUE #1601: 🐛 BUG: Unbound workers don’t respect subrequest limit in `--local` mode
### What version of `Wrangler` are you using?

2.0.24

### What operating system are you using?

Linux

### Describe the Bug

Miniflare recently updated to support new subrequest limits for Unbound workers (cloudflare/miniflare#274), but it requires the caller to pass `usageModel`. In `--local` mode, `wrangler dev` doesn’t support the new subrequest limits because it’s not passing the parameter.

I tested this locally, and passing `unbound` to the compiled Miniflare CLI results in the correct behaviour. 

I’ll put together a PR to read this from `wrangler.toml` and pass it through.

### PR DESCRIPTION
**Pull request by huw**
This is relatively simple—we just mirror the props structure of `<Remote />`, which already accepts `usageModel`. Fixes #1601.

I tested locally with `usageModel: undefined`, `usageModel: “bundled”` and `usageModel: “unbound”`—all worked fine. Please let me know if you want me to write any Jest tests. I don’t know Jest but I’m sure I could figure it out ^_^

Thanks for a nice clean repo, it’s very easy to work with!

### CODE REVIEW

**Comment by JacobMGEvans** [comment]
Happy to get this in. To fix the checks blocking the PR you can run `npm run fix` in the root of the project. Thanks 😄

**Comment by JacobMGEvans** [comment]
> Please let me know if you want me to write any Jest tests. I don’t know Jest but I’m sure I could figure it out ^_^

Please do. We like to have test with every addition or PR 😄 

> Thanks for a nice clean repo, it’s very easy to work with!

Well thank you! we appreciate the contribution 😄

**Comment by huw** [comment]
Done & added a couple of basic tests to at least guarantee the variable gets passed to the environment. Just FYI, `fix` doesn’t fix files in `.changeset`, but I feel like it’s supposed to since `check` looks at it.

**Comment by JacobMGEvans** [comment]
> Done & added a couple of basic tests to at least guarantee the variable gets passed to the environment. Just FYI, `fix` doesn’t fix files in `.changeset`, but I feel like it’s supposed to since `check` looks at it.

Hahaha yeah the `.changeset` `fix` after I had said that. I appreciate you doing it manually

**Pull request merged**
