### PR TITLE
Fixed routes with same paths but different methods from being overwritten on Windows

### PR DESCRIPTION
**Pull request by Mexican-Man**
This issue doesn't seem like it would be exclusive to Windows, but it made it into the latest release, so maybe it is. This PR works for me on Windows; can someone confirm it doesn't create duplicate paths on other OSes?

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Thanks for identifying this problem @Mexican-Man - and for the fix.

Please can you add the following test to **packages/wrangler/pages/functions/filepath-routing.test.ts** in this PR so that we can ensure we don't regress. Note that I have wrapped the current tests in a new `describe("filepath-routing")` block.

```ts
import { writeFileSync } from "node:fs";
import { runInTempDir } from "../../src/__tests__/helpers/run-in-tmp";
import { toUrlPath } from "../../src/paths";
import { compareRoutes, generateConfigFromFileTree } from "./filepath-routing";
import type { UrlPath } from "../../src/paths";
import type { HTTPMethod, RouteConfig } from "./routes";

describe("filepath-routing", () => {
  describe("compareRoutes()", () => { ... });

  describe("generateConfigFromFileTree", () => {
    runInTempDir();

    it("should generate a route entry for each file in the tree", async () => {
      writeFileSync(
        "foo.ts",
        `
      export function onRequestGet() {}
      export function onRequestPost() {}
      `
      );
      writeFileSync(
        "bar.ts",
        `
      export function onRequestPut() {}
      export function onRequestDelete() {}
      `
      );

      const entries = await generateConfigFromFileTree({
        baseDir: ".",
        baseURL: "/base" as UrlPath,
      });
      expect(entries).toEqual({
        routes: [
          {
            method: "PUT",
            module: ["bar.ts:onRequestPut"],
            routePath: "/base/bar",
          },
          {
            method: "DELETE",
            module: ["bar.ts:onRequestDelete"],
            routePath: "/base/bar",
          },
          {
            method: "GET",
            module: ["foo.ts:onRequestGet"],
            routePath: "/base/foo",
          },
          {
            method: "POST",
            module: ["foo.ts:onRequestPost"],
            routePath: "/base/foo",
          },
        ],
      });
    });
  });
});

...
```

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Approval from me once the test is in place.

**Comment by Mexican-Man** [comment]
@petebacondarwin I added your block, lmk if that fits what you were asking for.

**Comment by petebacondarwin** [comment]
I updated the changeset and commit messages, and merged via 91d89943cda26a197cb7c8d752d7953a97fac338.

**Pull request closed without merging**
