### PR TITLE
Don't skip generate tests

### LINKED ISSUE #2547: 🐛 BUG:  `wrangler generate` doesn't work on Windows
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

Windows

### Describe the Bug

wrangler generate geergit-backend worker-openapi

 ⛅️ wrangler 2.6.2 (update available 2.7.1)
-----------------------------------------------------
Creating a worker in geergit-backend from worker-openapi

✘ [ERROR] Failed to find "worker-openapi" in https://github.com/cloudflare/templates.git

unable to create a worker in geergit-backend using worker-openapi tempalte

### PR DESCRIPTION
**Pull request by penalosa**
What this PR solves / how to test:

Don't skip any tests. Specifically, the tests which checked the behaviour of `wrangler generate` were being skipped. This PR reverts that skipping (and depending on the test outcome will fix the failing tests)

Author has included the following, where applicable:

- [x] Tests
- ~[ ] Changeset~

Reviewer has performed the following, where applicable:

- [ ] Checked for inclusion of relevant tests
- [ ] Checked for inclusion of a relevant changeset
- [ ] Checked for creation of associated docs updates
- [ ] Manually pulled down the changes and spot-tested

Fixes #2547

### CODE REVIEW

**Comment by petebacondarwin** [comment]
I believe these were being skipped because we didn't want to have our unit tests rely upon external git cloning, which is slow, doesn't work offline, and is in danger of failing due to network issues, rather than problems with Wrangler.

Are you re-enabling these because we are moving the templates into this monorepo and have a way to configure it to run locally?

**Review by rozenmd — COMMENTED** [review]
These were intentionally skipped as they fetch a real repo that could change without us noticing: https://github.com/cloudflare/wrangler2/issues/2184

Are we planning to fix that?

**Comment by penalosa** [comment]
@petebacondarwin @rozenmd This was opened to try and reproduce https://github.com/cloudflare/wrangler2/issues/2547 in our tests. If it gets merged, it should be after the templates work from @JacobMGEvans, so that the git clones can be from a local git repository and we're not depending on network access. I'll mark this as a draft for now!

**Comment by penalosa** [comment]
Closing in favour of work to improve generate tests based on the templates migration: https://github.com/cloudflare/wrangler2/issues/1980

**Pull request closed without merging**
