### PR TITLE
fix: remove unwanted logging from `kv:bulk` operations

### PR DESCRIPTION
**Pull request by petebacondarwin**
There are two commits here. Look at them one at a time 😄

### CODE REVIEW

**Review by threepointone — APPROVED** [review]
Oh this is a good PR, thanks for this catch. 

But makes me wonder, maybe we should log a success message for these operations? I haven't checked what wrangler1 does, but I'm sure it's not _nothing_. 

Approving this one anyway, we can address it in a subsequent PR if you'd like.

**Comment by petebacondarwin** [comment]
OK. I'll merge this and then look into what W1 does.

**Comment by petebacondarwin** [comment]
Cripes! It looks like W1 has a "progress bar" while doing these bulk operations...

**Comment by petebacondarwin** [comment]
And as well as various messages, it also has confirmations for bulk deletes...

**Comment by petebacondarwin** [comment]
And does the putting/deleting in batches...

**Comment by threepointone** [comment]
The progress bar is something we can do later ofc, we can apply that for many things across the app. The success message I feel is kinda important. The confirmation message... hmm, I guess. I remember having to approve a -f flag for folks who didn't want it (in CI etc) but I wonder if it's useful at all.

**Comment by petebacondarwin** [comment]
Fixed up the `delete` operation here https://github.com/cloudflare/wrangler2/pull/552

**Pull request merged**
