### PR TITLE
Added optional shortcuts

### PR DESCRIPTION
**Pull request by ytkg**
Hi.
Added optional shortcuts.
`--local` is too long, so I wanted to start local mode with `-l`.

### CODE REVIEW

**Comment by threepointone** [comment]
Sure, why not :) Could you add a changeset as well? As described in the comment above this. We've started integrating it into our workflow, and want to see how people adjust to it.

**Comment by ytkg** [comment]
I added Changeset. Is it correct?

**Comment by threepointone** [comment]
Looks good, thank you!

**Review by threepointone — APPROVED** [review]
Good enhancement, thanks for the PR!

**Pull request merged**
